name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - name: Build
      run: appveyor.bat
